ControlFocus("Save As","","Edit1")
sleep(2000)
ControlSetText("Save As","","Edit1","C:\Joel\SeleniumProjects\IQuoteUIDB\src\test\resources\Documents\Actual.pdf")
sleep(2000)
ControlClick("Save As","","Button1")
sleep(2000)